# Pre-commit hooks for code quality
exclude: '^\.'
repos:
  # Code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^apps/.*\.py$
        exclude: ^apps/tests/.*|^apps/.*/tests/.*|^apps/.*/build/.*|^apps/.*/scripts/.*
      - id: ruff-format
        files: ^apps/.*\.py$
        exclude: ^apps/tests/.*|^apps/.*/tests/.*|^apps/.*/build/.*|^apps/.*/scripts/.*

  # Type checking with pyright - TODO: Enable after fixing all type errors
  # Currently disabled because:
  # - query_handler.py: pyright ignores conflict with ruff-format
  # - cwe_ingestion: needs type fixes for pg_chunk_store, parser
  # - pdf_worker: needs type fixes for conditional imports
  # Run manually with: poetry run pyright apps/chatbot/src
  # - repo: local
  #   hooks:
  #     - id: pyright
  #       name: pyright (type checking)
  #       entry: bash -c 'poetry run pyright apps/chatbot/src'
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       files: ^apps/chatbot/src/.*\.py$

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, ./apps, -x, "./apps/tests/**,./apps/**/tests/**,./apps/**/test_*.py,./apps/**/build/**,./apps/**/scripts/**", -ll, --skip, B608]
        pass_filenames: false

  # Secret scanning with trufflehog (uses installed binary)
  - repo: local
    hooks:
      - id: trufflehog
        name: trufflehog (secrets scan)
        # scans only the files pre-commit passes (i.e., staged/changed files)
        entry: bash -lc 'trufflehog filesystem --fail --no-update --results=verified,unknown "$@"'
        language: system
        types: [text]
        pass_filenames: true
        stages: [commit]
        # Skip common noisy paths; adjust as needed
        exclude: ^(apps/.*/tests/|apps/.*/build/|apps/.*/scripts/|tests/)

  # Semgrep - Advanced security scanning
  - repo: https://github.com/semgrep/semgrep
    rev: v1.89.0
    hooks:
      - id: semgrep
        args: ['--config=p/python', '--config=p/security-audit', '--exclude=**/tests/**', '--exclude=**/scripts/**', '--exclude=apps/cwe_ingestion/cwe_ingestion/parser.py', '--error', '--skip-unknown-extensions']
        pass_filenames: false

  # pip-audit - Dependency vulnerability scanning
  - repo: local
    hooks:
      - id: pip-audit-local
        name: pip-audit (dependency vulnerabilities)
        entry: bash -c 'poetry export -f requirements.txt --without-hashes -o /tmp/requirements.txt && pip-audit -r /tmp/requirements.txt --ignore-vuln GHSA-wj6h-64fc-37mp || true'
        language: system
        pass_filenames: false
        files: ^poetry\.lock$

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^apps/.*\.py$
        exclude: ^apps/tests/.*|^apps/.*/tests/.*|^apps/.*/build/.*|^apps/.*/scripts/.*
      - id: end-of-file-fixer
        files: ^apps/.*\.py$
        exclude: ^apps/tests/.*|^apps/.*/tests/.*|^apps/.*/build/.*|^apps/.*/scripts/.*
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
