[project]
# Name of the app and chatbot.
name = "CWE ChatBot"

# Description of the chatbot.
description = "A conversational AI for CWE (Common Weakness Enumeration) analysis"

# The default value for the auto collapse message threshold.
default_collapse_content = true

# Show the prompt playground
show_prompt_playground = false

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Authorize users to upload files with messages
multi_modal = false

# Authorize users to upload files with messages
file_upload = false

[features]
# Show the prompt playground
prompt_playground = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

[UI]
# Name of the app and chatbot.
name = "CWE ChatBot"

# Show the prompt playground
show_prompt_playground = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme]
    [UI.theme.light]
        #background = "#FAFAFA"
        #paper = "#FFFFFF"

        [UI.theme.light.primary]
            #main = "#F80061"
            #dark = "#980039"
            #light = "#FFE7EB"

    # Override default MUI dark theme. (Check theme.ts)
    [UI.theme.dark]
        #background = "#FAFAFA"
        #paper = "#FFFFFF"

        [UI.theme.dark.primary]
            #main = "#F80061"
            #dark = "#980039"
            #light = "#FFE7EB"

[meta]
generated_by = "1.3.2"