# GCP Service Account configuration for CWE ChatBot
# This file defines the minimal service account and IAM roles required

# Service Account Definition
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cwe-chatbot-sa
  annotations:
    # Service account description
    description: "Minimal service account for CWE ChatBot Cloud Run deployment"
    # Project binding
    project: "${GCP_PROJECT_ID}"

# IAM Policy Bindings
---
# Cloud Run Invoker role (minimal permission for Cloud Run execution)
apiVersion: iam.googleapis.com/v1
kind: Policy
metadata:
  name: cwe-chatbot-invoker-policy
spec:
  bindings:
    - role: roles/run.invoker
      members:
        - serviceAccount:cwe-chatbot-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    # Minimal logging permissions for Cloud Logging
    - role: roles/logging.logWriter
      members:
        - serviceAccount:cwe-chatbot-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com